name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        runtime: [win-x64, linux-x64]
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: src/vfzip/vfzip.csproj 

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $env:PROJECT_PATH
    - name: Build
      run: dotnet build $env:PROJECT_PATH --no-restore
    - name: Publish Windows
      run: dotnet publish $env:PROJECT_PATH --no-build --verbosity normal --self-contained -r ${{ matrix.runtime }}
      
