name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        runtime: [win-x64, linux-x64]
    runs-on: windows-latest
    env:
      PROJECT_PATH: src/vfzip/vfzip.csproj 
      ARTIFACTS_PATH: artifacts/

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }} -r ${{ matrix.runtime }}
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore -r ${{ matrix.runtime }} --self-contained -c release
    - name: Artifacts Folder
      run: mkdir -p ${{ env.ARTIFACTS_PATH }}
    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} --no-build --verbosity normal --self-contained -r ${{ matrix.runtime }} -o $ARTIFACTS_PATH -c release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: executable
        path: ${{ env.ARTIFACTS_PATH }}/vfzip*
        if-no-files-found: error
        retention-days: 0
